---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dzt.
--- DateTime: 2020/5/7 9:54 AM
---

print(type(nil==nil or 1 > nil))

--function returnX(KEYS, ARGS)
--    local current = redis.call('GET', KEYS[1])
--    if (currentARGS[1] > current)
--    then
--        redis.call('SET', KEYS[1], ARGS[1])
--        return true
--    else
--        return false
--    end
--end
--
--print(returnX({}))
--

local current=tonumber(redis.call('GET', KEYS[1]))
if (current==nil or tonumber(ARGV[1])>current)
then
    redis.call('SET', KEYS[1], ARGV[1])
    return 1
else
    return 0
end
